<item>
    <title>${title}</title>
    <link>http://127.0.0.1/wordpress/?p=${id}</link>
    <pubDate>${date}</pubDate>
    <dc:creator>admin</dc:creator>
    <guid isPermaLink="false">http://127.0.0.1/wordpress/?p=${id}</guid>
    <description></description>
    <content:encoded><![CDATA[${content}]]></content:encoded>
    <excerpt:encoded><![CDATA[]]></excerpt:encoded>
    <#--<wp:post_id>$it.Id</wp:post_id>-->
    <wp:post_date>${date}</wp:post_date>
    <wp:post_date_gmt>${date}</wp:post_date_gmt>
    <wp:comment_status>open</wp:comment_status>
    <wp:ping_status>open</wp:ping_status>
    <wp:post_name>${title}</wp:post_name>
    <wp:status>publish</wp:status>
    <wp:post_parent>0</wp:post_parent>
    <wp:menu_order>0</wp:menu_order>
    <wp:post_type>post</wp:post_type>
    <wp:post_password></wp:post_password>
    <wp:is_sticky>0</wp:is_sticky>
</item>